[package]
name = "soroban-auction-factory-contract"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["rlib"]

[dependencies]
soroban-sdk.workspace = true
emergency_guard = { path = "../emergency_guard", default-features = false }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
emergency_guard = { path = "../emergency_guard", default-features = false }

[features]
testutils = []